name: Deploy to K3s

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        sudo chmod +x /usr/local/bin/k3d

    - name: Start k3d cluster
      run: k3d cluster create my-cluster --agents 1

    - name: Get k3d kubeconfig
      run: |
        mkdir -p ~/.kube
        k3d kubeconfig get my-cluster > ~/.kube/config
        export KUBECONFIG=~/.kube/config
        kubectl config get-contexts

    - name: Deploy Nginx
      run: |
        kubectl apply -f nginx-deployment.yaml --validate=false

    - name: Stop k3d cluster (Optional)
      if: always()
      run: k3d cluster delete my-cluster
